## 310-geth-configmap.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-b-mcps-config
  labels:
    app: agent-b-mcps
data:
  NODE_ENV: development
  PORT: "3030"
  ZKFETCH_WRAPPER_URL: https://dev.zktls.zeroproofai.com
  ATTESTER_URL: https://dev.attester.zeroproofai.com
  RECLAIM_ADDRESS: "0xAe94FB09711e1c6B057853a515483792d8e474d0"
  ZPI_ZKPAY_URL: http://zpi-zkpay.mordor.svc.cluster.local:8080
  MERCHANT_WALLET_ADDRESS: "0x87597B1Cc790EC8678E7CB2C50aa9b8B023db195"
  NVM_ENVIRONMENT: sandbox
  NEVERMINED_TOKEN_URL: "https://api.sandbox.nevermined.app/api/v1/x402/permissions"
  NEVERMINED_VERIFY_URL: "https://api.sandbox.nevermined.app/api/v1/x402/verify"
  NEVERMINED_SETTLE_URL: "https://api.sandbox.nevermined.app/api/v1/x402/settle"
  NEVERMINED_VERIFY_SCHEMA: facilitator
  NEVERMINED_SCHEME: "nvm:card-delegation"
  NEVERMINED_NETWORK: stripe
  NEVERMINED_MANDATE_ID: "9a19e767-b2d4-4595-a2cb-3c022e43141d"
  NEVERMINED_PLAN_ID: "56632484305776997696847884128078087353328720197273726213760281865969044835771"
  NEVERMINED_AGENT_ID: "55421718781137411526334773514004031298273880127422637573346674984691580888757"
  NEVERMINED_PAY_TO: agent-b-farm
  NEVERMINED_USE_TOKEN_EXCHANGE: "true"
  NEVERMINED_VERIFY_LEGACY_RETRY: "false"
  SERVER_BASE_URL: https://dev.agentb.zeroproofai.com
  NEVERMINED_DANGER_ACCEPT_INVALID_CERTS: "false"
  NEVERMINED_HTTP_TRACE: "true"